/********************************************************************
* ./include/Dictionary_DmpEvtBgoAttLen.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error ./include/Dictionary_DmpEvtBgoAttLen.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableDictionary_DmpEvtBgoAttLen();
extern void G__cpp_setup_inheritanceDictionary_DmpEvtBgoAttLen();
extern void G__cpp_setup_typetableDictionary_DmpEvtBgoAttLen();
extern void G__cpp_setup_memvarDictionary_DmpEvtBgoAttLen();
extern void G__cpp_setup_globalDictionary_DmpEvtBgoAttLen();
extern void G__cpp_setup_memfuncDictionary_DmpEvtBgoAttLen();
extern void G__cpp_setup_funcDictionary_DmpEvtBgoAttLen();
extern void G__set_cpp_environmentDictionary_DmpEvtBgoAttLen();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "DmpEvtBgoAttLen.h"
#include "DmpEvtBgoAttLen.h~"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__Dictionary_DmpEvtBgoAttLenLN_TClass;
extern G__linked_taginfo G__Dictionary_DmpEvtBgoAttLenLN_TBuffer;
extern G__linked_taginfo G__Dictionary_DmpEvtBgoAttLenLN_TMemberInspector;
extern G__linked_taginfo G__Dictionary_DmpEvtBgoAttLenLN_TObject;
extern G__linked_taginfo G__Dictionary_DmpEvtBgoAttLenLN_vectorlEshortcOallocatorlEshortgRsPgR;
extern G__linked_taginfo G__Dictionary_DmpEvtBgoAttLenLN_vectorlEdoublecOallocatorlEdoublegRsPgR;
extern G__linked_taginfo G__Dictionary_DmpEvtBgoAttLenLN_string;
extern G__linked_taginfo G__Dictionary_DmpEvtBgoAttLenLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__Dictionary_DmpEvtBgoAttLenLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__Dictionary_DmpEvtBgoAttLenLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__Dictionary_DmpEvtBgoAttLenLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__Dictionary_DmpEvtBgoAttLenLN_DmpEvtBgoAttLen;

/* STUB derived class for protected member access */
